### ISSUE TITLE
run libfuzzer in mac

### ISSUE THREAD

**Issue by zheng-yan-max** [Dor1s/libfuzzer-workshop#9]
hello author,I am so interesting in libfuzzer.I want to know can I run libfuzzer on a MAC?

**Comment by Dor1s** [comment]
Yes, you can.

**Comment by zheng-yan-max** [comment]
> Yes, you can.

Do you have any tutorials that I haven't found running on the MAC yet

**Comment by Dor1s** [comment]
It's very similar to Linux use case. You can either use `-fsanitize=fuzzer` if you clang is new enough, or in the worst case compile libFuzzer into a shared library and link your fuzz targets with it.

**Comment by Darshana133** [comment]
Could you please give me an insight where I'm wrong in my cmake command to build libFuzzer on macOS from source. The cmake command I used is:

```
cmake -S llvm -B build -G Ninja \
    -DLLVM_ENABLE_PROJECTS="clang;lldb" \
    -DLLVM_ENABLE_RUNTIMES="libcxx" \
    -DCMAKE_BUILD_TYPE=Debug \
    -DLLVM_TARGETS_TO_BUILD="AArch64" \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DLLVM_USE_SANITIZER=Address \
    -DLLVM_USE_SANITIZE_COVERAGE=On \
    -DLLDB_USE_SYSTEM_DEBUGSERVER=ON \
    -DCMAKE_C_COMPILER=/opt/homebrew/opt/llvm/bin/clang \
    -DCMAKE_CXX_COMPILER=/opt/homebrew/opt/llvm/bin/clang++  \
    -DCMAKE_OSX_ARCHITECTURES='arm64' \
    -DCMAKE_CXX_FLAGS="-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
```
 This builds without any error. But when I try to run libFuzzer  using a sample program, I got the error:
  
```
ld: warning: ignoring duplicate libraries: ‘-lc++’
ld: library ‘llvm-project/build/lib/clang/19/lib/darwin/libclang_rt.fuzzer_osx.a’ not found
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

```

Could you please tell me where I'm wrong. Should I build compiler-rt project. I tried, but there were some errors. I believe the errors occur because libFuzzer was not build. But clang was build as I could compile a sample C program. Thanks a lot for your time.

**Comment by Dor1s** [comment]
@Darshana133 please try following the suggestions listed in https://stackoverflow.com/questions/76115746/libclang-rt-fuzzer-osx-a-is-not-found-on-macos
